version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: deshi-sahayak-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: deshi-sahayak-hub
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - deshi-sahayak-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: deshi-sahayak-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redispassword
    networks:
      - deshi-sahayak-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deshi-sahayak-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      API_VERSION: v1
      
      # Database
      MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/deshi-sahayak-hub?authSource=admin
      
      # Redis
      REDIS_URL: redis://:redispassword@redis:6379
      
      # JWT
      JWT_SECRET: your-super-secret-jwt-key-development
      JWT_EXPIRE: 7d
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-development
      JWT_REFRESH_EXPIRE: 30d
      
      # Email (Development - use Ethereal or Mailtrap)
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_USER: your-ethereal-username
      SMTP_PASS: your-ethereal-password
      FROM_EMAIL: noreply@deshisahayak.com
      FROM_NAME: Deshi Sahayak Hub
      
      # Frontend
      FRONTEND_URL: http://localhost:5173
      
      # Admin
      ADMIN_EMAIL: admin@deshisahayak.com
      ADMIN_PHONE: +919876543210
      
      # Rate Limiting
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      
      # Logging
      LOG_LEVEL: info
      LOG_FILE: logs/app.log
    
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    
    depends_on:
      - mongodb
      - redis
    
    networks:
      - deshi-sahayak-network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: deshi-sahayak-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000/api/v1
      VITE_SOCKET_URL: http://localhost:5000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
    depends_on:
      - backend
    networks:
      - deshi-sahayak-network

# Networks
networks:
  deshi-sahayak-network:
    driver: bridge

# Volumes
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
